Repository codeit-1st-team5/rolling, pull requests merged in 2023-11, with the labels that each got.

#1 [feat] 버튼 구현
  jsconfig.json
  src/assets/icons/circle-button-icon.svg
  src/components/button/Button.js
  src/styles/globalStyles.js
Labels: 💫feat

#11 [UI] 버튼 width와 margin 수정
  src/components/button/Button.js
Labels: 🎨UI

#12 [Chore] 메인 버튼의 className prop 추가
  src/components/button/Button.js
Labels: ⚙️chore

#7 [feat] landing 페이지 레이아웃 제작
  src/assets/img/landing_img_01.png
  src/assets/img/landing_img_02.png
  src/components/button/Button.js
  src/constants/landingData.js
  src/pages/LandingPage.js
Labels: 🎨UI

#14 [refactor] 하단의 버튼에 의해 내용이 가려지는 버그 수정
  src/pages/LandingPage.js
Labels: 🐛bug

#15 [feat] useRequest 추가
  src/apis/api.js
  src/hooks/useRequest.js
Labels: 💫feat

#16 Feat: 텍스트 에디터 생성
  package-lock.json
  package.json
  src/components/textarea/Textarea.js
Labels: 💫feat

#19 Refactor: 버튼 속성 추가
  src/components/button/Button.js
Labels: 🍀refactor

#24 [feat] 아웃라인 버튼 컴포넌트 제작
  src/components/button/OutlinedButton.js
Labels: 💫feat

#27 [feat] media query 변수화
  src/index.js
  src/styles/media.js
Labels: ⚙️chore, 💫feat

#21 [feat] nav 컴포넌트 제작
  .eslintrc.js
  src/assets/icons/logo-icon.svg
  src/components/nav/Nav.js
Labels: 💫feat

#28 [feat] cardlist 컴포넌트 구현
  src/assets/icons/card-list-pattern-icon.svg
  src/components/CardList/CardList.js
  src/components/CardList/mockData.js
Labels: 💫feat

#34 [refactor] useRequest 훅에서, fetcher 함수도 return하도록 수정
  src/hooks/useRequest.js
Labels: 🍀refactor

#42 [refactor] 컴포넌트 폴더명 파스칼 케이스로 통일
  src/components/Badges/CoworkerBadge.js
  src/components/Badges/FamilyBadge.js
  src/components/Badges/FriendBadge.js
  src/components/Badges/OtherBadge.js
  src/components/Card/Card.js
Labels: 🍀refactor

#32 [feat] create post page layout 제작
  src/assets/icons/box-slelected-icon.svg
  src/components/button/Button.js
  src/components/createPost/CaseStyle.js
  src/components/createPost/ColorCase.js
  src/components/createPost/ImageCase.js
  src/components/createPost/PostForm.js
  src/pages/CreatePostPage.js
Labels: 💫feat

#31 [refactor] Nav 바 이름 변경
  src/components/Layout.js
  src/components/Nav/Nav.js
Labels: 🍀refactor

#50 [fix] .eslintrc.js env 설정으로 process 관련 문제 해결
  .eslintrc.js
  src/assets/icons/arrow_right.svg
  src/components/CardList/Card.js
  src/components/CardList/CardList.js
  src/components/CardList/mockData.js
  src/components/ListTitle/ListTitle.js
  src/components/ListTitle/index.js
  src/pages/ListPage.js
Labels: ⚙️chore

#40 [feat] 무한 스크롤 구현
  src/assets/img/loading-spinner.gif
  src/components/Card/Card.js
  src/components/Skeleton/SkeletonCard.js
  src/components/Spinner/Spinner.js
  src/hooks/useRequest.js
  src/pages/PostPage.js
Labels: 💫feat

#45 [feat] 이모지 팝오버 기능 추가
  .github/ISSUE_TEMPLATE/🐞-bug.md
  .github/ISSUE_TEMPLATE/💫-feature.md
  .github/pull_request_template.md
  .prettierrc.js
  README.md
  package-lock.json
  package.json
  public/index.html
  src/assets/fonts/font.css
  src/assets/icons/arrow_down.svg
  src/assets/icons/emoji-add-icon.svg
  src/components/Emoji/Emoji.js
  src/components/button/ArrowDownButton.js
Labels: 💫feat

#53 [refactor] nav에 의해 가려지는 내용이 없도록 margin-top 설정
  src/pages/CreatePostPage.js
  src/pages/LandingPage.js
Labels: 🍀refactor

#55 [refactor] 미디어쿼리 변수로 수정
  src/components/createPost/CaseStyle.js
  src/pages/CreatePostPage.js
  src/pages/LandingPage.js
Labels: 🍀refactor

#62 [feat] 메세지 카드 추가 컴포넌트 추가
  src/assets/icons/card-add-button-icon.svg
  src/components/Card/AddCard.js
  src/pages/PostPage.js
Labels: 🎨UI

#60 [feat] 에러 페이지 디자인 생성
  src/assets/img/error-img.png
  src/pages/ErrorPage.js
Labels: 🎨UI

#61 [feat] post/{id} 페이지 레이아웃
  src/components/Card/Card.js
  src/pages/PostPage.js
Labels: 🎨UI

#64 [feat] 날짜 형식 계산 함수 추가
  package-lock.json
  package.json
  src/utils/calcCreateAt.js
Labels: 💫feat

#59 [refactor] CreatePostPage 에 대한 route 설정
  src/index.js
Labels: 🍀refactor

#66 [refactor] userequest hook 사용
  src/components/CardList/CardList.js
Labels: 🍀refactor

#73 [feat] post-page-layout 구현
  src/constants/.gitkeep
  src/constants/postPageConstant.js
  src/pages/PostPage.js
Labels: 💫feat

#75 [refactor] 카드 컨텐츠 api 형식에 맞게 데이터 렌더링
  src/components/Card/AddCard.js
  src/components/Card/Card.js
  src/index.js
Labels: 🍀refactor

#72 [refactor] skeleton ui 반응형 디자인별 사이즈 추가
  src/components/Skeleton/SkeletonCard.js
Labels: 🍀refactor

#71 [feat] 인기 롤링 페이퍼 리액션 수대로 정렬, 페이징 구현
  src/components/CardList/ReactionCardList.js
  src/components/CardList/RecentCardList.js
  src/components/CardList/index.js
  src/pages/ListPage.js
Labels: 💫feat

#43 [feat] 공유 기능 추가
  public/index.html
  src/assets/icons/share-icon.svg
  src/components/Layout.js
  src/components/ShareTab/KakaoShareButton.js
  src/components/ShareTab/LinkShareButton.js
  src/components/ShareTab/ShareTab.js
  src/utils/openToast.js
Labels: 💫feat

#82 [feat] Post 페이지 Header-Service 생성
  src/components/Emoji/Emoji.js
  src/components/HeaderService/HeaderService.js
  src/components/Layout.js
  src/pages/PostPage.js
Labels: 💫feat

#85 [fix] Layout.js에 toastContainer 임포트
  src/components/Layout.js
Labels: 🐛bug

#57 [refactor] 컴포넌트 폴더명 변경(createPost -> Create)
  src/components/CreatePost/CaseStyle.js
  src/components/CreatePost/ColorCase.js
  src/components/CreatePost/ImageCase.js
  src/components/CreatePost/PostForm.js
  src/pages/CreatePostPage.js
Labels: 🍀refactor

#86 [refactor] 공유 기능 리팩토링
  src/components/ShareTab/KakaoShareButton.js
  src/components/ShareTab/LinkShareButton.js
  src/components/ShareTab/ShareTab.js
Labels: 🍀refactor

#89 [refactor] 중복된 import문 삭제
  src/index.js
Labels: 🐛bug

#87 [feat] post/{id}/edit 페이지 작성
  src/assets/icons/trash-icon.svg
  src/components/Card/Card.js
  src/index.js
  src/pages/PostPage.js
Labels: 💫feat

#95 [refactor] post{id} page 전체적인 리팩토링
  src/components/Card/AddCard.js
  src/components/Card/Card.js
  src/constants/postPageConstant.js
  src/hooks/useIntersectionObserver.js
  src/pages/PostPage.js
Labels: 🐛bug, 🍀refactor, 🛠fix

#97 [refactor] Header-service 모든 페이지에서 제거
  package-lock.json
  package.json
  src/components/HeaderService/HeaderService.js
  src/components/Layout.js
Labels: 🍀refactor

#100 [refactor] PostPage에 Header-Service 수정
  src/components/Emoji/Emoji.js
  src/components/HeaderService/HeaderService.js
  src/components/button/ArrowDownButton.js
  src/pages/PostPage.js
Labels: 🍀refactor

#102 [refactor] 토스트메세지 css 코드 위치 수정
  src/components/ShareTab/LinkShareButton.js
  src/utils/openToast.js
Labels: 🍀refactor, 🛠fix

#103 [Fix] 리스트 배경이미지 선택코드 수정
  src/components/CreatePost/ImageCase.js
Labels: 🛠fix

#105 [refactor] 버튼 폴더명 변경
  src/components/Button/ArrowDownButton.js
  src/components/Button/Button.js
  src/components/Button/OutlinedButton.js
  src/components/Card/Card.js
  src/components/CreatePost/PostForm.js
  src/components/Emoji/Emoji.js
  src/components/Modal/CardModal.js
  src/components/ShareTab/ShareTab.js
  src/pages/CreateMessagePage.js
  src/pages/CreatePostPage.js
  src/pages/LandingPage.js
  src/pages/ListPage.js
  src/pages/PostPage.js
Labels: 🍀refactor

#101 [refactor] 첫 렌더링 시 왼쪽 버튼 안보이도록 수정
  src/components/CardList/CardList.js
Labels: 🍀refactor

#106 [refactor] 카드 터치스크롤 구현
  src/components/CardList/Card.js
  src/components/CardList/CardList.js
Labels: 🍀refactor

#98 [refactor] post page 리팩토링
  package-lock.json
  package.json
  src/components/Card/AddCard.js
  src/components/Card/Card.js
  src/hooks/useRequest.js
  src/pages/PostPage.js
Labels: 🍀refactor, 💫feat

#108 [refactor] button import conflict 해결
  src/pages/PostPage.js
Labels: 🛠fix

#109 [refactor] background image 디자인 추가
  src/pages/PostPage.js
Labels: 💫feat

#110 [feat] headerService에 ProfileAndMessage 컴포넌트 추가
  src/components/HeaderService/HeaderService.js
  src/components/HeaderService/ProfileAndMessage.js
Labels: 💫feat

#112 [refactor] landing페이지에 고배율 이미지 적용
  src/assets/img/landing_img_01.png
  src/assets/img/landing_img_01.webp
  src/assets/img/landing_img_02.png
  src/assets/img/landing_img_02.webp
  src/components/Image/WebpLoader.js
  src/constants/landingData.js
  src/pages/LandingPage.js
Labels: 🍀refactor

#116 [ refactor] createMessagePage, createPostPage에 로딩, 성공/실패 toast 추가
  src/components/CreateMessage/MessageForm.js
  src/components/CreatePost/CaseStyle.js
  src/components/CreatePost/ImageCase.js
  src/components/Spinner/Spinner.js
  src/pages/CreateMessagePage.js
  src/pages/CreatePostPage.js
Labels: 🍀refactor

#118 [refactor] CreatePostPage의 컬러/이미지 탭 스타일 변경
  src/components/CreatePost/PostForm.js
Labels: 🍀refactor

#119 [refactor] 카드 테두리 경계 수정
  src/components/CardList/Card.js
Labels: 🍀refactor

#120 [Refactor] Post페이지 및 Header-Service 수정
  src/components/HeaderService/HeaderService.js
  src/components/Layout.js
  src/pages/PostPage.js
Labels: 🍀refactor

#121 [refactor] editPage에서 모달창 생성 막기
  src/components/Modal/CardModal.js
  src/pages/PostPage.js
Labels: 🍀refactor

#123 [refactor] Card컴포넌트에서 ProfileAndMessage컴포넌트를 사용할 수 있도록 수정
  src/components/CardList/Card.js
  src/components/HeaderService/HeaderService.js
  src/components/HeaderService/ProfileAndMessage.js
Labels: 🍀refactor

#124 [UI] 레이아웃 수정
  src/components/CardList/Card.js
  src/components/CreatePost/PostForm.js
  src/components/HeaderService/HeaderService.js
  src/pages/LandingPage.js
Labels: 🎨UI

#125 [refactor] Card 컴포넌트의 ProfileAndMessage 컴포넌트 style 변경
  src/components/HeaderService/ProfileAndMessage.js
Labels: 🍀refactor

#126 [feat] EmojiBedge 제작
  src/components/Badges/EmojiBedge.js
Labels: 💫feat

#127 [refactor] post layout 디테일 마무리
  src/components/Card/Card.js
  src/pages/PostPage.js
Labels: 🍀refactor

#129 [feat] 카드 이모지 표시 적용
  src/components/CardList/Card.js
  src/components/Emoji/Emoji.js
Labels: 💫feat

#130 [refactor] listpage loading일 때 spinner 적용
  src/components/CardList/CardList.js
Labels: 🍀refactor

#131 [feat] Post 페이지 header-service안에 topreactions 추가
  src/components/Badges/EmojiBedge.js
  src/components/Emoji/Emoji.js
Labels: 💫feat

#132 [refactor] README.md 수정
  README.md
Labels: 🍀refactor

#128 [refactor] card content 말줄임 부분 수정
  src/apis/service/config.js
  src/components/Card/Card.js
  src/pages/PostPage.js
Labels: 🍀refactor

#134 [refactor] edit 페이지에서 데이터가 없을때 수정
  src/pages/PostPage.js
Labels: 🍀refactor

#139 [feat] 이모지를 누르면 추가하고 보여지는 기능
  src/components/Emoji/Emoji.js
Labels: 💫feat

#144 [Design] listPage의 카드, 모달창에 애니메이션 추가
  src/components/Card/Card.js
  src/components/Modal/CardModal.js
  src/components/Modal/ModalPortal.js
  src/pages/PostPage.js
Labels: 🌈frontend

#145 [refactor] edit 페이지 메세지 비어있을때 디자인 수정
  src/assets/img/new-message.gif
  src/pages/PostPage.js
Labels: 🍀refactor

#146 Refactor: 모달 애니메이션 수정
  public/imgs/heart.png
  src/components/Modal/CardModal.js
  src/pages/PostPage.js
  src/styles/zIndex.js
Labels: 🌈frontend

#148 [Feat] floating button 생성 및 모달 애니메이션 수정
  src/assets/icons/letter-opened-svgrepo-com.svg
  src/assets/icons/list-heart-svgrepo-com.svg
  src/assets/icons/setting-5-svgrepo-com.svg
  src/components/Button/FloatingButton.js
  src/components/Modal/CardModal.js
  src/pages/PostPage.js
Labels: 💫feat, 🛠fix
